# Generated by Django 5.1.1 on 2024-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
