# Generated by Django 5.1.1 on 2024-09-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_quiz_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz',
            new_name='course',
        ),
    ]
