# Generated by Django 5.1.1 on 2024-09-27 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizsubmission',
            name='quiz',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.quiz'),
        ),
    ]
